// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FirstJourneyRules","status":true,"description":"Overworld rules and content","parameters":{}},
{"name":"FirstJourney","status":true,"description":"Map combat and prototype UI","parameters":{}},
{"name":"FirstJourneyPresentation","status":true,"description":"Map targeting, portraits and movement","parameters":{}}
];
